build:
  version: "1.0"

contact:
  message: "Welcome to simple bank microservice, this properties to test record object - production profile"
  contact-details:
    name: "KP - changed - updated - trying change - 11"
    email: "vietkhoa93@gmail.com"