build:
  version: "1.0"

contact:
  message: "Welcome to simple bank microservice, this properties to test record object - prod profile"
  contact-details:
    name: "KP"
    email: "vietkhoa93@gmail.com"