server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
#    import: "optional:configserver:http://configserver:8071/" #Running in container
    import: "optional:configserver:http://localhost:8071/" #Running in local

  datasource:
#    url: 'jdbc:postgresql://postgres:5433/accounts' #Running in container
    url: 'jdbc:postgresql://localhost:5433/accounts' #Running in local
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"