services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_multi_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_MULTIPLE_DATABASES: accounts,cards,loans
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  configserver:
    image: "khoapv93/configserver:v2"
    container_name: configserver-ms
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      test: ["CMD", "curl", "-f", "localhost:8071/actuator/health/readines"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-base-config

  accounts:
    image: "khoapv93/accounts:v2"
    container_name: account-ms
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      configserver:
        condition: service_healthy # Must to define health check like above steps first
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5433/accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "khoapv93/loans:v2"
    container_name: loans-ms
    ports:
      - 8090:8090
    depends_on:
      postgres:
        condition: service_healthy
      configserver:
        condition: service_healthy # Must to define health check like above steps first
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5433/loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "khoapv93/cards:v2"
    container_name: cards-ms
    ports:
      - 9000:9000
    depends_on:
      postgres:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5433/cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  simplebank:
    driver: "bridge"