spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "/Users/phamvietkhoa/learning-code/microservices-spring/simple-bank-code/configserver/src/main/resources/config"
          search-locations: "classpath:/config"

# ---------- Fetch config from github repo ----------
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          default-label: main
#          timeout: 5
#          uri: "github-repo-uri"
#          clone-on-start: true
#          force-pull: true

encrypt:
  key: "A5F9A534645FA234512B8EF39A12E" #key to test encrypt function of spring cloud, keep the key private
server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true